### ISSUE TITLE
How can I show the month with letters instead of numbers ?

### ISSUE THREAD

**Issue by miguejs** [byzg/ion2-datetime-picker#5]
![screen shot 2017-05-29 at 5 35 53 pm](https://cloud.githubusercontent.com/assets/9428793/26563278/5dbcd0a2-4495-11e7-830e-8ad1748d527f.png)

**Comment by byzg** [comment]
@miguejs At now there is no this feature in master. I'm working with it but if it is urgent for you, you can use alfa-version of this feature in [pickerFormat branch](https://github.com/byzg/ion2-datetime-picker/tree/pickerFormat) : ```[pickerFormat]="'MMM'"```

**Comment by byzg** [comment]
@miguejs It is done, you can use ```pickerFormat``` in 1.1.9 version. Now I close the issue, feel free to reopen it if it's needed
